### ISSUE TITLE
plexWatch.pl not running

### ISSUE THREAD

**Issue by kylerw** [needo37/plexWatch#2]
The plexWatch process does not seem to be running. I am using a DB from my previous install so the setup of the web portion is all kosher but the DB size is not growing and no new items are being added.

**Comment by RageInvader** [comment]
I'm having same issues... plexWatch.db won't update since first install.
Which permissions did u use to get it to work... I tried unRAID's 'newperms' but it doesn't work.

**Comment by needo37** [comment]
What permissions do you have set currently?

**Comment by RageInvader** [comment]
Mainly using unraids's 'newperms' command. 
I get this when using 'ls -l' command
drwxrwxrwx 3 nobody users 272 May 12 21:04 plexWatch

**Comment by needo37** [comment]
And what about inside that directory?

**Comment by RageInvader** [comment]
-rw-rw-rw- 1 nobody users    599 May 12 20:41 config.php
-rw-rw-rw- 1 nobody users  13276 May 12 20:45 config.pl
drwxrwxrwx 2 nobody users    168 May 12 20:30 db_backups/
-rw-rw-rw- 1 nobody users   7650 May 12 20:30 debug.log
-rw-rw-rw- 1 nobody users  66560 May 12 20:31 plexWatch.db
-rw-rw-rw- 1 nobody users    499 May 12 20:30 plexWatch.log
-rw-rw-rw- 1 nobody users 181361 May 12 20:29 plexWatch.pl

It all looks fine to me, still can't figure out why it won't update...

**Comment by needo37** [comment]
Well... the script has to be executable or it won't run. chmod 777 plexWatch.pl or chmod 755 it.

**Comment by RageInvader** [comment]
ahhhhhhhhh Knew it would be something simple.... 

Thanks very much absolute fantastic docker :)
